### PR TITLE
WMM.COF for 2020 epoch

### PR DESCRIPTION
**Pull request by Wlodarski**
WMM.COF updated with the newly published 2020 epoch model

### CODE REVIEW

**Comment by cmweiss** [comment]
Thanks!

**Comment by Wlodarski** [comment]
If you would have merged the pull request instead of closing it, the bug would have been solved and you would have not to do yourself what has been done for you.

**Comment by cmweiss** [comment]
I thought I did that but... I don't know what happened.

**Comment by cmweiss** [comment]
Merge and close is what I clicked on.

**Comment by Wlodarski** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

**Pull request closed without merging**
